run:
  timeout: 5m
  tests: true
  skip-dirs:
    - test_data
    - bin

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
  disable:
    - gosec
    - unused
    - gosimple
    - structcheck
    - deadcode
    - varcheck

linters-settings:
  errcheck:
    check-blank: false
  govet:
    check-shadowing: false
  staticcheck:
    checks: ["all", "-SA1019", "-SA1029"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/loader/
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 10